name: Java CI with Gradle
run-name: Publish client release
on:
  release:
    types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    env:
      GH_USER: ${{ github.actor }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Login to the Docker Hub
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKER_USER }}
        password: ${{ secrets.DOCKER_TOKEN }}

    - name: Push release image to Docker Hub
      run: |
        NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
        echo "New version is - ${NEW_VERSION}"
        docker build -t erneman/pomaranch-client .
        docker tag erneman/pomaranch-client erneman/pomaranch-client:${NEW_VERSION}
        docker push -a erneman/pomaranch-client
