name: Java CI with Gradle
run-name: Publish client release
on: [push]
  # release:
  #   types: [published]

jobs:
  publish-release:
    runs-on: ubuntu-latest
    env:
      GH_USER: ${{ vars.GH_USER }}
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
    steps:
    - name: Print envs
      run: |
        echo $GH_USER
        3chp $GH_TOKEN
    - name: Checkout the code
      uses: actions/checkout@v3

    - name: Login to the container registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: $GH_USER
        password: $GH_TOKEN

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '17'
        distribution: 'corretto'

    - name: Build with Gradle
      run: ./gradlew clean build

    - name: Build and push
      run: |
        NEW_VERSION=$(echo "${GITHUB_REF}" | cut -d "/" -f3)
        echo "New version is - ${NEW_VERSION}"
        docker build -t ghcr.io/present-is-a-gift/pomaranch-client:${NEW_VERSION} .
        docker push ghcr.io/present-is-a-gift/pomaranch-client:${NEW_VERSION}
